[profile.default]
src = "src"
out = "out"
test = 'test/foundry'
cache_path = 'cache/foundry'
verbosity = 3
optimize = true
optimizer_runs = 200

libs = [
    "lib",
    # We provide a set of useful contract utilities
    # in the lib directory of @layerzerolabs/toolbox-foundry:
    #
    # - forge-std
    # - ds-test
    # - solidity-bytes-utils
    "node_modules/@layerzerolabs/toolbox-foundry/lib",
    "node_modules",
]

remappings = [
    # from NPM
    "ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test",
    "forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std",
    "@layerzerolabs/=node_modules/@layerzerolabs/",
    
    # from Git submodules
    "@kleros/kleros-v2-contracts/=lib/kleros-v2/contracts/src/",
    "@kleros/dispute-resolver-interface-contract-0.8/=lib/dispute-resolver-interface-contract/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "solidity-bytes-utils/=lib/solidity-bytes-utils/",
    "@kleros/erc-792/=lib/erc-792/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
