[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@layerzerolabs/lz-evm-oapp-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/",
    "@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/",
    "@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/",
    "@kleros/kleros-v2-contracts/=lib/kleros-v2/contracts/src/",
    "@kleros/dispute-resolver-interface-contract-0.8/=lib/dispute-resolver-interface-contract/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "solidity-bytes-utils/=lib/solidity-bytes-utils/",
    "@kleros/erc-792/=lib/erc-792/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
